# Generated by Django 3.2 on 2022-01-21 00:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departamento', '0002_alter_departamento_nombre_corto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60, verbose_name='Nombre')),
                ('apellidos', models.CharField(max_length=60, unique=True, verbose_name='Apellidos')),
                ('trabajo', models.CharField(choices=[('CONTADOR', 'CONTADOR'), ('ADMINISTRADOR', 'ADMINISTRADOR'), ('ECONOMISTA', 'ECONOMISTA'), ('OTRO', 'OTRO')], max_length=60, verbose_name='Trabajo')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empleado_departamento', to='departamento.departamento')),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
                'ordering': ['apellidos'],
            },
        ),
    ]
