# Generated by Django 3.2 on 2022-01-20 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('nombre_corto', models.CharField(max_length=20, verbose_name='Nombre Corto')),
                ('no_activo', models.BooleanField(default=False, verbose_name='No Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Dapertamento',
                'verbose_name_plural': 'Dapertamentos',
                'ordering': ['nombre'],
            },
        ),
    ]
