# Generated by Django 3.2 on 2022-01-21 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('departamento', '0002_alter_departamento_nombre_corto'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='departamento',
            unique_together={('nombre', 'nombre_corto')},
        ),
    ]
